name: PyTest

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Coverage Report
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Package and Dependencies
        run: pip install .[tests]

      - name: Run PyTest and Generate Coverage Report
        run: |
          pytest --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov=bruker_to_ismrmrd | tee pytest-coverage.txt
        shell: bash

      - name: Upload PyTest Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-py${{ matrix.python-version }}
          path: |
            pytest-coverage.txt
            pytest.xml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
