name: Report PyTest

on:
  workflow_run:
    workflows:
      - PyTest
    types:
      - completed

jobs:
  coverage_report_pr:
    name: Coverage report
    if: >-
      ${{ github.event.workflow_run.event == 'pull_request' &&
          github.event.workflow_run.conclusion != 'cancelled' &&
          github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
    steps:
      # use the results of python 3.12, consider this as target platform
      - name: Download PyTest report artifact for py3.12
        uses: actions/download-artifact@v8
        with:
          name: pytest-report-py3.12
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR number
        id: pr-context
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TARGET_REPO: ${{ github.repository }}
          PR_BRANCH: |-
            ${{
              (github.event.workflow_run.head_repository.owner.login != github.event.workflow_run.repository.owner.login)
                && format('{0}:{1}', github.event.workflow_run.head_repository.owner.login, github.event.workflow_run.head_branch)
                || github.event.workflow_run.head_branch
            }}
        run: |
          gh pr view --repo "${PR_TARGET_REPO}" "${PR_BRANCH}" \
              --json 'number' --jq '"number=\(.number)"' \
              >> "${GITHUB_OUTPUT}"

      - name: Post PyTest Coverage Comment
        id: coverage_comment
        uses: MishaKav/pytest-coverage-comment@v1.12.2
        with:
          issue-number: ${{ steps.pr-context.outputs.number }}
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml

      - name: Post Failure Comment if Coverage Comment failed
        if: steps.coverage_comment.outputs.coverageHtml == ''
        uses: edumserrano/find-create-or-update-comment@v3
        with:
          issue-number: ${{ steps.pr-context.outputs.number }}
          body-includes: '<!-- Pytest Coverage Comment: ${{ github.job }} -->'
          comment-author: 'github-actions[bot]'
          body: |
            <!-- Pytest Coverage Comment: ${{ github.job }} -->
            ### :x: PyTest Coverage Report was not found

            Check the PyTest Workflow
          edit-mode: replace

  coverage_report_push_main:
    name: Coverage report push main
    if: >-
      ${{ github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'main' &&
          github.event.workflow_run.conclusion != 'cancelled' &&
          github.event.workflow_run.conclusion != 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: pytest-report-py3.12

      - name: Post PyTest Coverage Comment on push main
        id: coverage_comment
        uses: MishaKav/pytest-coverage-comment@v1.12.2
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
